version: "3.8"

services:
    app:
        build: .
        container_name: calculator-app
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - mongo
        environment:
            - PORT=8080
            - DB_URI=mongodb://mongo:27017/logDB
        networks:
            - app-network

    mongo:
        image: mongo:6
        container_name: mongo-db
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_DATABASE: logDB
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network

volumes:
    mongo-data:

networks:
    app-network:
